resources:
  - name: S_PS_R_GIT_0016_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: jfbetapipeorg/Org_test_Automation

pipelines:
  - name: pipelines_S_PS_R_GIT_0016
    steps:
      - name: S_PS_R_GIT_0016
        type: Bash
        configuration:
#           nodePool: win_2019
          inputResources:
            - name: S_PS_R_GIT_0016_GitRepo
        execution:
          onExecute:
            - echo $res_S_PS_R_GIT_0016_GitRepo_committerLogin
            - echo $res_S_PS_R_GIT_0016_GitRepo_isRelease
