pipelines:
  - name: build
    type: Bash
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - 8.16.0
    execution:
      onExecute:
        - echo 'hello world'
       
