resources:
  - name:  checkCron
    type: CronTrigger
    configuration:
      interval: "0 0/1 * 1/1 *"
pipelines:
  - name: bashStep1
    steps:
      - name: build
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - 8.17.0
        execution:
          onExecute:
            - echo 'hello world'
       
