pipelines:
  - name: pipe1
    steps:
      - name: test_step_1
        type: Bash
        configuration:
          integrations:
            - name: rak_test_slack      
        execution:
          onExecute:
            - send_notification rak_test_slack "pipeline_name failed in step step_name at step_url"
          onSuccess:
            - send_notification rak_test_slack 
          onFailure:
            - send_notification rak_test_slack  --text "pipeline_name failed in step step_name at step_url"
          
