artifactoryIntegration: myArtifactoryIntegration
 
GitRepo:
  name: myGitRepo
  gitProvider: myGitIntegration
  path: myorg/myrepo
  branches:
    include: master
 
Image:
  name: myDockerImage
  sourceRepository: mySourceRepo     
 
Pipeline:
  name: myDockerPipeline
 
DockerBuild:
  name: myDockerBuild  
  dockerFileName: Dockerfile
  dockerImageName: <image name>
 
DockerPush:
  targetRepository: docker-local
 
Bash:
  name: myBashStep
